# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jeremiah's Code Site
tagline:          'Common Lisp and Other Stuff'
description:      ""
url:              https://jl2.github.io
baseurl:          https://jl2.github.io/

author:
  name:           'Jeremiah'
  url:            https://jl2.github.io

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jl2/jl2.github.io


plugins: [jekyll-paginate]
paginate_path: "page:num"

